#!/bin/bash
if test -z "$1";then
    exit 2;
fi

tmpLog=$1
echo ""
while [[ true ]]; do
    ## show the lateast penultimate line
    str=$(tail -2 $tmpLog | head -1)
    #echo -en "\r$str"
    echo -e "\r\r$str"
    sleep 4
done
