#!/bin/bash
logDir='/home/ltan/var/log'
if test ! -d $logDir;then
    mkdir -p $logDir
fi

natProcess=`ps aux | grep 'natapp -au' | grep 'th'`
if test -z "$natProcess";then
    natppCount=0
else
    natppCount=`echo $natProcess | wc -l`
    natPid=`echo $natProcess |awk '{print $2}'`
fi

if test $natppCount -lt 1;then
    /data/env/natapp -authtoken 14ae8f66afcc9370 1> $logDir/natapp.log 2>&1 &
else
    echo "natapp PID: $natPid is running..."`date` > $logDir/natapp.log
fi
